<script lang="ts">
	import Slider from '$lib/components/controls/Slider.svelte';
	import { exponentialMovingAverage } from '$lib/math/adam.js';
	let beta1 = $state(0.9); let beta2 = $state(0.99); let scale = $state(1);
	const gradients = [1,1,1,-1,-1,-1,2,0.2,0.2,-0.2,-0.2,0.8];
	const data = $derived.by(() => { const g=gradients.map(v=>v*scale); const m=exponentialMovingAverage(g,beta1); const v=exponentialMovingAverage(g.map(x=>x*x),beta2); return {g,m,v,n:m.map((x,i)=>x/(Math.sqrt(v[i])+1e-8))}; });
</script>
<div class="demo"><div class="controls"><Slider bind:value={beta1} min={0} max={.99} step={.01} label="β₁ — direction"/><Slider bind:value={beta2} min={.9} max={.999} step={.001} label="β₂ — échelle"/><Slider bind:value={scale} min={.1} max={3} step={.1} label="échelle du gradient"/></div><div class="legend"><span class="g">gₜ</span><span class="m">mₜ</span><span class="v">vₜ</span><span class="n">mₜ/(√vₜ+ε)</span></div><svg viewBox="0 0 720 240" role="img" aria-label="Gradients, moments et ratio Adam"><line x1="30" y1="120" x2="710" y2="120" stroke="var(--color-border)"/><line x1="30" y1="25" x2="30" y2="215" stroke="var(--color-border)"/>{#each data.g as gradient,i}<line x1={40+i*58} y1="25" x2={40+i*58} y2="215" stroke="var(--color-border)" opacity=".25"/><circle cx={40+i*58} cy={120-gradient*30} r="4" fill="var(--color-surprise)"/><circle cx={40+i*58} cy={120-data.m[i]*30} r="4" fill="var(--color-positive)"/><circle cx={40+i*58} cy={120-data.v[i]*22} r="4" fill="var(--color-belief)"/><circle cx={40+i*58} cy={120-data.n[i]*30} r="4" fill="var(--color-agent)"/>{/each}</svg><p class="note">Le dénominateur suit une échelle au carré : Adam lisse la direction avec <b>mₜ</b> et normalise avec <b>vₜ</b>.</p></div>
<style>.demo{display:grid;gap:1rem}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.legend{display:flex;gap:1rem;font: .8rem var(--font-mono)}.legend span:before{content:'● ';}.g{color:var(--color-surprise)}.m{color:var(--color-positive)}.v{color:var(--color-belief)}.n{color:var(--color-agent)}svg{width:100%;background:var(--color-surface);border-radius:var(--radius-md)}.note{color:var(--color-text-muted);font-size:.9rem}@media(max-width:650px){.controls{grid-template-columns:1fr}}</style>
