<script lang="ts">
	import Slider from '$lib/components/controls/Slider.svelte';
	import { adamStep, createAdamState } from '$lib/math/adam.js';
	let scenario=$state('β₂ trop grand'); let beta2=$state(.999); let alpha=$state(.1); let epsilon=$state(1e-8);
	const scenarios=['α trop grand','β₂ trop grand','β₁ trop grand','ε trop petit'];
	const run=$derived.by(()=>{let theta=[1,1],s=createAdamState(2);let last={mHat:[0,0],vHat:[0,0],effectiveLearningRate:[0,0],update:[0,0]};for(let i=0;i<24;i++){const g=scenario==='β₂ trop grand'&&i===12?[5,.1]:scenario==='β₁ trop grand'&&i>12?[-1,-1]:[.2,.2];const r=adamStep(theta,g,s,{alpha:scenario==='α trop grand'?Math.max(alpha,.4):alpha,beta1:scenario==='β₁ trop grand'?.99:.9,beta2,epsilon:scenario==='ε trop petit'?1e-12:epsilon});theta=r.theta;s=r.state;last=r;}return {theta,last};});
	const diagnosis=$derived(scenario==='β₂ trop grand'?'mémoire du second moment potentiellement obsolète':scenario==='β₁ trop grand'?'direction qui réagit lentement':'inspecter la norme des mises à jour et le dénominateur');
</script>
<div class="demo"><div class="scenario-list">{#each scenarios as item}<button class:active={scenario===item} onclick={()=>scenario=item}>{item}</button>{/each}</div><div class="controls"><Slider bind:value={alpha} min={.01} max={.8} step={.01} label="α"/><Slider bind:value={beta2} min={.9} max={.999} step={.001} label="β₂"/><Slider bind:value={epsilon} min={1e-8} max={.01} step={.0001} label="ε"/></div><div class="diagnosis"><b>Diagnostic :</b> {diagnosis}</div><div class="metrics"><span>‖θ‖ ≈ {Math.hypot(...run.theta).toFixed(3)}</span><span>‖m̂‖ ≈ {Math.hypot(...run.last.mHat).toFixed(3)}</span><span>‖v̂‖ ≈ {Math.hypot(...run.last.vHat).toFixed(3)}</span><span>‖Δθ‖ ≈ {Math.hypot(...run.last.update).toFixed(3)}</span></div></div>
<style>.demo{display:grid;gap:1rem}.scenario-list{display:flex;flex-wrap:wrap;gap:.5rem}.scenario-list button{border:1px solid var(--color-border);background:var(--color-surface);color:var(--color-text);padding:.45rem .7rem;border-radius:var(--radius-md);cursor:pointer}.scenario-list button.active{border-color:var(--color-surprise);color:var(--color-surprise)}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.diagnosis{padding:.75rem 1rem;border-left:3px solid var(--color-surprise);background:var(--color-surface)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem;font: .8rem var(--font-mono)}.metrics span{padding:.6rem;border:1px solid var(--color-border);border-radius:var(--radius-md)}@media(max-width:650px){.controls,.metrics{grid-template-columns:1fr 1fr}}</style>
